project:
  type: website
  output-dir: docs
  resources:
    - docs/.nojekyll

website:
  title: "Visualizing Indirect Effects"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: simulations.qmd
        text: Simulations
      - href: case_study.qmd
        text: Case Study - Blowfly larvae
      - href: kallan_case_study.qmd
        text: Case Study - Bighorn Sheep

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    toc-depth: 5
    number-depth: 5
